name: 'npm bump'
description: 'npm i && npm test && npm version {major,minor,patch} && npm publish as an action.'
branding:
  icon: box
  color: blue
inputs:
  git_email:
    description: 'The email address used to create the version commit with.'
    required: true
  git_username:
    description: 'The name to use for the version commit. e.g. github.actor'
    required: true
  newversion:
    description: 'The version bump type to perform (e.g. major, minor, path). See npm version docs for more info.  Pass this as an interactive variable.'
    required: true
  push_version_commit:
    description: 'Run git push --follow-tags after running npm version.  Enable this if you dont configure a prepublishOnly hook that pushes git commits.'
    required: false
    default: false
  publish_cmd:
    description: 'The command to run after npm version.  Useful if you are just using npm to version a package, but not publish to npm (like an action).'
    required: false
    default: 'npm publish'
  github_token:
    description: 'Pass the secrets.GITHUB_TOKEN to enable gh-release capabilities.'
    required: false
  npm_token:
    description: 'An npm token scoped for publishing.  Used to create the release.'
    required: false
outputs:
  release_tag:
    description: "The name of the created git tag as described by git describe --tags"
    value: ${{ steps.release-tag-retreiver.outputs.release-tag }}
runs:
  using: 'composite'
  steps:
    - run: git config --global user.email "${{ inputs.git_email }}"
      shell: bash
    - run: git config --global user.name "${{ inputs.git_username }}"
      shell: bash
    - run: npm version ${{ inputs.newversion }}
      shell: bash
      env:
        GH_RELEASE_GITHUB_API_TOKEN: ${{ inputs.github_token }}
    - run: echo "release-tag=$(git describe --tags)" >> $GITHUB_OUTPUT
      id: release-tag-retreiver
      shell: bash
    - run: |
        if [ "${{ inputs.push_version_commit }}" = "true" ]; then
          git push --follow-tags
        else
          echo "Skipping git push --follow-tags"
        fi
      shell: bash
    - run: ${{ inputs.publish_cmd }}
      shell: bash
      env:
        GH_RELEASE_GITHUB_API_TOKEN: ${{ inputs.github_token }}
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
