name: npm bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        type: choice
        options:
          - patch
          - minor
          - major
          - custom
        default: 'patch'
        required: true
      newversion:
        description: 'Custom version (only used when version_type is "custom")'
        required: false

env:
  FORCE_COLOR: 1

permissions:
  contents: write
  id-token: write

concurrency: # prevent concurrent releases
  group: npm-bump
  cancel-in-progress: true

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    outputs:
      tagName: ${{ steps.npm-bump.outputs.release_tag }}
    steps:
    - uses: actions/checkout@v6
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'
    - run: npm i
    - name: Configure git author
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    - name: Version and release
      uses: bcomnes/npm-bump@master
      id: npm-bump
      with:
        version_type: ${{ github.event.inputs.version_type }}
        newversion: ${{ github.event.inputs.newversion }}
        publish_cmd: npm run release # dont publish to a registry. set up something else in a different script
        github_token: ${{ secrets.GITHUB_TOKEN }} # built in actions token.  Passed to gh-release if in use.
    - run: echo ${{ steps.npm-bump.outputs.release_tag }}
